config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :pots
  #get 'home/index'
  resources :pots
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'home/about'
  get 'pots/destroy'
  get 'pots/trash_em'
  get 'home/trash_em_all'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pot.rb
class Pot < ApplicationRecord
	#belongs_to :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         #has_many :pots
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pots = Pot.all
  end

  def about
      @pots = Pot.all
  
  end

 # def cancel_class
  #  @cancel_class = Pot.destroy
   # redirect_to pots_url, notice: 'You have cancelled this class'
 # end
def trash_em
  @trash_em = Pot.destroy_all
  redirect_to pots_url, notice: 'Class Bookign Successfully Cancel'
end

def trash_em_all
    @trash_em_all = Pot.all.destroy_all
    redirect_to pots_url, notice: 'All Classes Were Successfully Canceled.'
  end

  
end

app/controllers/pots_controller.rb
 class PotsController < ApplicationController
  before_action :set_pot, only: %i[ show edit update destroy ]
  #before_action :correct_user, only: %i[edit update destroy]
  before_action :authenticate_user!

  # GET /pots or /pots.json
  def index
    @pots = Pot.all
  end

  # GET /pots/1 or /pots/1.json
  def show
    @pots = Pot.all
  end

  # GET /pots/new
  def new
    @pot = Pot.new
  end

  # GET /pots/1/edit
  def edit
  end

  # POST /pots or /pots.json
  def create
    @pot = Pot.new(pot_params)

    respond_to do |format|
      if @pot.save
        format.html { redirect_to pot_url(@pot), notice: "Class was successfully booked." }
        format.json { render :show, status: :created, location: @pot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pots/1 or /pots/1.json
  def update
    respond_to do |format|
      if @pot.update(pot_params)
        format.html { redirect_to pot_url(@pot), notice: "Class booking was successfully updated." }
        format.json { render :show, status: :ok, location: @pot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pots/1 or /pots/1.json
 
 def destroy
    @pot = Pot.find(params[:id])
    @pot.destroy

    redirect_to pots_url
  end


  def correct_user
    @ticker = current_user.pots.find_by(id: params[:id])
    redirect_to pots_path, notice: "Not authorized to edit this class!" if @ticker.nil?
  end
 

def setLesson
  :lesson
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pot
      @pot = Pot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pot_params
      params.require(:pot).permit(:lesson, :booked, :class_type, :user_name, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pots_helper.rb
module PotsHelper
end

app/views/home/_flash.html.erb
<br/>
<% flash.each do |name, msg| %>
      <div class="alert alert-warning alert-dismissable" role="alert" >
            <button class="btn-close" data-bs-dismiss="alert">
                  <small><sup>x</sup></small>
            </button>
            <%= content_tag(:div, msg) %>
      </div>
<% end %>

app/views/home/_footer.html.erb
<br/><br/><br/><br/><br/>
<p><center>Copyright (c) Elkie Smullen 2023</center></p>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Pottery Classes", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        

        <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to "Booked Classes", home_about_path, class: "nav-link" %>
        </li>      
        <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
        <li class="nav-item">
              <%= button_to "Logout", destroy_user_session_path, :method => :delete, class: "nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>

        <% end %>

        
        


        
       
      </ul>
     
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_include_tag  "turbo" ,type: "module" %>
<h1>My Booked Classes</h1>

  <table class="table  table-bordered table-hover">
  <thead class="table-light">
    <tr>
      <th>Lesson</th>
      <th>Class Type</th>
      <th>Email</th>
      <th colspan="2"></th>
    </tr>
  </thead>
   <tbody>

   <% @pots.each do |pot| %>
      <% if pot.user_id == current_user.id %>
        <tr>
          <td><%= pot.lesson %></td>
          <td><%= pot.class_type %></td>
          <td><%= current_user.email %></td>
          <td><center><%= link_to 'Edit this booking', edit_pot_path(pot) %></center></td>
          <td><center><%= link_to 'Cancel Class', pot, data: { turbo: true, turbo_method: :delete }, class: 'btn btn-danger'%></center></td>
        </tr>
        <% end %>
     <% end %>
    </tbody>
    </table>
<%= link_to "Book Another Class", pots_path, class: 'btn btn-secondary' %>

<br/><br/><br/>
<%= link_to 'Delete All Classes', home_trash_em_all_path, class: 'btn btn-danger', data: {confirm: 'Are you sure? '} %>
</div>

app/views/home/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<% if user_signed_in? %>

  <center><h1>Available Classes</h1></center>
  

   <div class="jumbotron m-3 bg-light p-5">
      <h2>Handbuilding classes</h2>
        <p>Learn techniques such as:
          <ul>
            <li>Slab</li>
            <li>Coil</li>
            <li>Pinch</li>
            <li>Underglazing</li>
            <li>Glazing</li>
          </ul>
          to create your own unique creations out of clay!
        </p>

      <div class="row">
        <div class="col-sm-4 mb-3 mb-sm-0">
           <div class="card">  
              <%= image_tag("sman2.jpg", :alt => "snowman") %>
              <div class="card-body">
                <h5 class="card-title">Christmas Decorations</h5>
                <p class="card-text">Make your very own Christmas tree decorations. Choose form a wide variety of cutters and stencils</p>
               
                <center><%= link_to "Book Now", new_pot_path(@post, :lesson => "Christmas Decorations", :class_type => "Handbuilding"), class: "btn btn-primary", type: 'submit' %></center>
 
              </div>
            </div>
      </div>
      <div class="col-sm-4"> 
        <div class="card">  
            <%= image_tag("angels.jpg", :alt => "angels") %>
            <div class="card-body">
              <h5 class="card-title">Christmas Ornaments</h5>
              <p class="card-text">Create your own slab, pinch or coil Christmas angel ornaments</p>
              <center><%= link_to "Book Now", new_pot_path(@post, :lesson => "Christmas Ornaments", :class_type => "Handbuilding"), class: "btn btn-primary" %></center>
            </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="card">  
            <%= image_tag("sculpture.jpg", :alt => "sculpture") %>
            <div class="card-body">
              <h5 class="card-title">Sculpture Class</h5>
              <p class="card-text">Want to try something a little different? Create your own slab, pinch or coil Sculpture, choose from terracotta, earthenware or stoneware clay</p>
              <center><%= link_to "Book Now", new_pot_path(@post, :lesson => "Sculpture Class", :class_type => "Handbuilding"), class: "btn btn-primary" %></center>
            </div>
        </div>
      </div>
    </div>
  </div>

  <div class="jumbotron m-3 bg-light p-5">
    <h2>Wheel classes</h2>
    <p>Try your hand at the potters wheel. Learn to center and trim pottery. Classes are available to:
      <ul>
        <li>Individuals</li>
        <li>Couples</li>
        <li>Groups/ Parties</li>
        <li>Beginners</li>
        <li>Intermediate throwers</li>
        <li>Advance throwers</li>
      </ul>
    </p>
    <br/>

    <div class="row">
      <div class="col-sm-4 mb-3 mb-sm-0">
         <div class="card">  
            <%= image_tag("thrown2.jpg", :alt => "mug") %>
            <div class="card-body">
              <h5 class="card-title">Make your own Mug</h5>
              <p class="card-text">Make your very own handmade wheel thrown mug, learn to center and throw</p>
             <center><%= link_to "Book Now", new_pot_path(@post, :lesson => "Make your own Mug", :class_type => "Wheel"), class: "btn btn-primary" %></center>
            </div>
          </div>
      </div>
      <div class="col-sm-4">
        <div class="card">  
            <%= image_tag("gonk.jpg", :alt => "gonk") %>
            <div class="card-body">
              <h5 class="card-title">Christmas Gonk</h5>
              <p class="card-text">Create your own slab, pinch or coil Christmas gonk ornaments</p>
              <center><%= link_to "Book Now", new_pot_path(@post, :lesson => "Christmas Gonk", :class_type => "Wheel"), class: "btn btn-primary" %></center>
            </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="card">  
            <%= image_tag("bowl.jpg", :alt => "bowl") %>
            <div class="card-body">
              <h5 class="card-title">Stoneware bowl</h5>
              <p class="card-text">Learn to center large quantities of clay and create your own stoneware bowl</p>
              <center><%= link_to "Book Now", new_pot_path(@post, :lesson => "Stoenware bowl", :class_type => "Wheel"), class: "btn btn-primary" %></center>
            </div>
        </div>
      </div>
  </div> 

  <% else %>

   <center><h1>Available Classes</h1></center>
   <p>Chose from a selection of handbuilding and wheel throwing classes. Sign up today to book a class</p>
    <div class="jumbotron m-3 bg-light p-5">
        <h2>Handbuilding classes</h2>
          <p>Learn techniques such as:
            <ul>
              <li>Slab</li>
              <li>Coil</li>
              <li>Pinch</li>
              <li>Underglazing</li>
              <li>Glazing</li>
            </ul>
            to create your own unique creations out of clay!
          </p>

      <div class="row">
        <div class="col-sm-4 mb-3 mb-sm-0">
           <div class="card">  
              <%= image_tag("sman2.jpg", :alt => "snowman") %>
              <div class="card-body">
                <h5 class="card-title">Christmas Decorations</h5>
                <p class="card-text">Make your very own Christmas tree decorations. Choose form a wide variety of cutters and stencils</p>
              </div>
            </div>
        </div>
        <div class="col-sm-4"> 
          <div class="card">  
              <%= image_tag("angels.jpg", :alt => "angels") %>
              <div class="card-body">
                <h5 class="card-title">Christmas Ornaments</h5>
                <p class="card-text">Create your own slab, pinch or coil Christmas angel ornaments</p>   
              </div>
          </div>
          <br/><center><%= link_to "Sign Up Now", new_user_registration_path, class: "btn btn-primary" %></center>
        </div>

        <div class="col-sm-4">
          <div class="card">  
              <%= image_tag("sculpture.jpg", :alt => "sculpture") %>
              <div class="card-body">
                <h5 class="card-title">Sculpture Class</h5>
                <p class="card-text">Want to try something a little different? Create your own slab, pinch or coil Sculpture, choose from terracotta, earthenware or stoneware clay</p>
               
              </div>
          </div>
      </div>
    </div>
  </div>

  <div class="jumbotron m-3 bg-light p-5">
    <h2>Wheel classes</h2>
     <p>Try your hand at the potters wheel. Learn to center and trim pottery. Classes are available to:
      <ul>
        <li>Individuals</li>
        <li>Couples</li>
        <li>Groups/ Parties</li>
        <li>Beginners</li>
        <li>Intermediate throwers</li>
        <li>Advance throwers</li>
      </ul>
    </p>
    <br/>
  <div class="row">
    <div class="col-sm-4 mb-3 mb-sm-0">
       <div class="card">  
          <%= image_tag("thrown2.jpg", :alt => "mug") %>
          <div class="card-body">
            <h5 class="card-title">Make your own Mug</h5>
            <p class="card-text">Make your very own handmade wheel thrown mug, learn to center and throw</p>
          </div>
        </div>
    </div>
    <div class="col-sm-4">
      <div class="card">  
          <%= image_tag("gonk.jpg", :alt => "gonk") %>
          <div class="card-body">
            <h5 class="card-title">Christmas Gonk</h5>
            <p class="card-text">Create your own slab, pinch or coil Christmas gonk ornaments</p>
            
          </div>
      </div>
      <br/><center><%= link_to "Sign Up Now", new_user_registration_path, class: "btn btn-primary" %></center>
    </div>
    <div class="col-sm-4">
      <div class="card">  
          <%= image_tag("bowl.jpg", :alt => "bowl") %>
          <div class="card-body">
            <h5 class="card-title">Stoneware bowl</h5>
            <p class="card-text">Learn to center large quantities of clay and create your own stoneware bowl</p>
           
          </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pottery App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render 'home/navbar' %>

    <div class="container">
      <%= render 'home/flash' %>
      
      <br/><br/>
        <%= yield %>
    </div>

    <%= render 'home/footer' %>

  </body>
</html>

app/views/pots/_editform.html.erb
<%= form_with(model: pot) do |form| %>
  <% if pot.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pot.errors.count, "error") %> prohibited this pot from being saved:</h2>

      <ul>
        <% pot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 
  <div>
    <%= form.label :lesson, style: "display: block" %>
    <%= form.text_field :lesson, autocomplete: "lesson", class:'form-control', value: params[:lesson], value: pot.lesson %>

  </div>

  <div>
    <%= form.label :class_type, style: "display: block" %>
    <%= form.text_field :class_type, autocomplete: "class_type", class:'form-control', value: params[:class_type], value: pot.class_type %>
  </div>

  <div>
   
    <%= form.text_field :email, autocomplete: "email", class:'form-control', value: current_user.email, type: :hidden %>
  </div>

  <div>   
    <%= form.number_field :user_id, class:'form-control', id: :pot_user_id, value: current_user.id, type: :hidden %>
  </div>
  <br/>
  <div>
    
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
 Edit Class
<% end %>
  </div>
<% end %>

app/views/pots/_form.html.erb
<%= form_with(model: pot) do |form| %>
  <% if pot.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pot.errors.count, "error") %> prohibited this pot from being saved:</h2>

      <ul>
        <% pot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 
  <div>
    <%= form.label :lesson, style: "display: block" %>
    <%= form.text_field :lesson, autofocus: true, autocomplete: "lesson", class:'form-control' %>

  </div>

  <div>
    <%= form.label :class_type, style: "display: block" %>
    <select id="formselect" class="form-select", :value => @class_type>
        <option>Handbuilding</option>
        <option>Wheel</option>
      </select>
  </div>

  <div>
    <%= form.label :user_name, style: "display: block" %>
    <%= form.text_field :user_name, autocomplete: "user_name", class:'form-control' %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, class:'form-control', :value => params[:user_id] %>
  </div>

  <div>
    
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
 Book Class
<% end %>
  </div>
<% end %>

app/views/pots/_pot.html.erb
<div id="<%= dom_id pot %>">
 
  <table class="table table-bordered table-hover">
  <thead class="table-light">
    <tr>
      <th>Lesson</th>
      <th>Class Type</th>
      <th>Email</th>
      <th colspan="2"></th>
    </tr>
  </thead>
   <tbody>
      <tr>
          <td><%= pot.lesson %></td>
          <td><%= pot.class_type %></td>  
          <td><%= current_user.email %></td>
          <td><center><%= link_to 'Edit booking', edit_pot_path(pot) %></center></td>
        </tr>
      </tbody>
    </table>
</div>
<%= link_to "Back to my Classes", home_about_path, class: 'btn btn-secondary' %>

app/views/pots/edit.html.erb
<div class="col-md-6 offset-md-3">
  <div class="jumbotron m-3 bg-light p-5">
    <h1>Edit Class</h1>

    <%= render "editform", pot: @pot %>

    <br>

    <div>
      <%= link_to "Show this class", @pot %> |
      <%= link_to "Back to classes", pots_path %>
    </div>
  </div>
</div>

app/views/pots/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<% if user_signed_in? %>

  <center><h1>Available Classes</h1></center>
  

   <div class="jumbotron m-3 bg-light p-5">
      <h2>Handbuilding classes</h2>
        <p>Learn techniques such as:
          <ul>
            <li>Slab</li>
            <li>Coil</li>
            <li>Pinch</li>
            <li>Underglazing</li>
            <li>Glazing</li>
          </ul>
          to create your own unique creations out of clay!
        </p>

      <div class="row">
        <div class="col-sm-4 mb-3 mb-sm-0">
           <div class="card">  
              <%= image_tag("sman2.jpg", :alt => "snowman") %>
              <div class="card-body">
                <h5 class="card-title">Christmas Decorations</h5>
                <p class="card-text">Make your very own Christmas tree decorations. Choose form a wide variety of cutters and stencils</p>
               
                <center><%= link_to "Book Now", new_pot_path(@post, :lesson => "Christmas Decorations", :class_type => "Handbuilding"), class: "btn btn-primary", type: 'submit' %></center>
 
              </div>
            </div>
      </div>
      <div class="col-sm-4"> 
        <div class="card">  
            <%= image_tag("angels.jpg", :alt => "angels") %>
            <div class="card-body">
              <h5 class="card-title">Christmas Ornaments</h5>
              <p class="card-text">Create your own slab, pinch or coil Christmas angel ornaments</p>
              <center><%= link_to "Book Now", new_pot_path(@post, :lesson => "Christmas Ornaments", :class_type => "Handbuilding"), class: "btn btn-primary" %></center>
            </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="card">  
            <%= image_tag("sculpture.jpg", :alt => "sculpture") %>
            <div class="card-body">
              <h5 class="card-title">Sculpture Class</h5>
              <p class="card-text">Want to try something a little different? Create your own slab, pinch or coil Sculpture, choose from terracotta, earthenware or stoneware clay</p>
              <center><%= link_to "Book Now", new_pot_path(@post, :lesson => "Sculpture Class", :class_type => "Handbuilding"), class: "btn btn-primary" %></center>
            </div>
        </div>
      </div>
    </div>
  </div>

  <div class="jumbotron m-3 bg-light p-5">
    <h2>Wheel classes</h2>
    <p>Try your hand at the potters wheel. Learn to center and trim pottery. Classes are available to:
      <ul>
        <li>Individuals</li>
        <li>Couples</li>
        <li>Groups/ Parties</li>
        <li>Beginners</li>
        <li>Intermediate throwers</li>
        <li>Advance throwers</li>
      </ul>
    </p>
    <br/>

    <div class="row">
      <div class="col-sm-4 mb-3 mb-sm-0">
         <div class="card">  
            <%= image_tag("thrown2.jpg", :alt => "mug") %>
            <div class="card-body">
              <h5 class="card-title">Make your own Mug</h5>
              <p class="card-text">Make your very own handmade wheel thrown mug, learn to center and throw</p>
             <center><%= link_to "Book Now", new_pot_path(@post, :lesson => "Make your own Mug", :class_type => "Wheel"), class: "btn btn-primary" %></center>
            </div>
          </div>
      </div>
      <div class="col-sm-4">
        <div class="card">  
            <%= image_tag("gonk.jpg", :alt => "gonk") %>
            <div class="card-body">
              <h5 class="card-title">Christmas Gonk</h5>
              <p class="card-text">Create your own slab, pinch or coil Christmas gonk ornaments</p>
              <center><%= link_to "Book Now", new_pot_path(@post, :lesson => "Christmas Gonk", :class_type => "Wheel"), class: "btn btn-primary" %></center>
            </div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="card">  
            <%= image_tag("bowl.jpg", :alt => "bowl") %>
            <div class="card-body">
              <h5 class="card-title">Stoneware bowl</h5>
              <p class="card-text">Learn to center large quantities of clay and create your own stoneware bowl</p>
              <center><%= link_to "Book Now", new_pot_path(@post, :lesson => "Stoneware Bowl", :class_type => "Wheel"), class: "btn btn-primary" %></center>
            </div>
        </div>
      </div>
  </div> 

  <% else %>

   <center><h1>Available Classes</h1></center>
   <p>Chose from a selection of handbuilding and wheel throwing classes. Sign up today to book a class</p>
    <div class="jumbotron m-3 bg-light p-5">
        <h2>Handbuilding classes</h2>
          <p>Learn techniques such as:
            <ul>
              <li>Slab</li>
              <li>Coil</li>
              <li>Pinch</li>
              <li>Underglazing</li>
              <li>Glazing</li>
            </ul>
            to create your own unique creations out of clay!
          </p>

      <div class="row">
        <div class="col-sm-4 mb-3 mb-sm-0">
           <div class="card">  
              <%= image_tag("sman2.jpg", :alt => "snowman") %>
              <div class="card-body">
                <h5 class="card-title">Christmas Decorations</h5>
                <p class="card-text">Make your very own Christmas tree decorations. Choose form a wide variety of cutters and stencils</p>
              </div>
            </div>
        </div>
        <div class="col-sm-4"> 
          <div class="card">  
              <%= image_tag("angels.jpg", :alt => "angels") %>
              <div class="card-body">
                <h5 class="card-title">Christmas Ornaments</h5>
                <p class="card-text">Create your own slab, pinch or coil Christmas angel ornaments</p>   
              </div>
          </div>
          <br/><center><%= link_to "Sign Up Now", new_user_registration_path, class: "btn btn-primary" %></center>
        </div>

        <div class="col-sm-4">
          <div class="card">  
              <%= image_tag("sculpture.jpg", :alt => "sculpture") %>
              <div class="card-body">
                <h5 class="card-title">Sculpture Class</h5>
                <p class="card-text">Want to try something a little different? Create your own slab, pinch or coil Sculpture, choose from terracotta, earthenware or stoneware clay</p>
               
              </div>
          </div>
      </div>
    </div>
  </div>

  <div class="jumbotron m-3 bg-light p-5">
    <h2>Wheel classes</h2>
     <p>Try your hand at the potters wheel. Learn to center and trim pottery. Classes are available to:
      <ul>
        <li>Individuals</li>
        <li>Couples</li>
        <li>Groups/ Parties</li>
        <li>Beginners</li>
        <li>Intermediate throwers</li>
        <li>Advance throwers</li>
      </ul>
    </p>
    <br/>
  <div class="row">
    <div class="col-sm-4 mb-3 mb-sm-0">
       <div class="card">  
          <%= image_tag("thrown2.jpg", :alt => "mug") %>
          <div class="card-body">
            <h5 class="card-title">Make your own Mug</h5>
            <p class="card-text">Make your very own handmade wheel thrown mug, learn to center and throw</p>
          </div>
        </div>
    </div>
    <div class="col-sm-4">
      <div class="card">  
          <%= image_tag("gonk.jpg", :alt => "gonk") %>
          <div class="card-body">
            <h5 class="card-title">Christmas Gonk</h5>
            <p class="card-text">Create your own slab, pinch or coil Christmas gonk ornaments</p>
            
          </div>
      </div>
      <br/><center><%= link_to "Sign Up Now", new_user_registration_path, class: "btn btn-primary" %></center>
    </div>
    <div class="col-sm-4">
      <div class="card">  
          <%= image_tag("bowl.jpg", :alt => "bowl") %>
          <div class="card-body">
            <h5 class="card-title">Stoneware bowl</h5>
            <p class="card-text">Learn to center large quantities of clay and create your own stoneware bowl</p>
           
          </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pots/new.html.erb
<div class="col-md-6 offset-md-3">
  <div class="jumbotron m-3 bg-light p-5">

    <h1>Book A Class</h1>

    <div class="form-group">
      <%= render "form", pot: @pot %>

      <br>

      <div>
        <%= link_to "Back to pots", pots_path %>
      </div>
    </div>
  </div>
</div>

app/views/pots/show.html.erb
<%= render @pot %>

<div>
  

 
</div>